# Generated by Django 3.2.5 on 2021-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
