# Generated by Django 3.2.5 on 2021-07-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
