# Generated by Django 3.2.5 on 2021-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_post_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_status',
            field=models.BooleanField(default=False),
        ),
    ]
