# Generated by Django 3.2.5 on 2021-07-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_thread_post_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='post_count',
            new_name='modified_detector',
        ),
    ]
