# Generated by Django 3.2.5 on 2021-07-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_post_count_thread_modified_detector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='modified_detector',
            field=models.IntegerField(default=0),
        ),
    ]
