# Generated by Django 3.2.5 on 2021-07-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_thread_modified_detector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='modified_detector',
        ),
    ]
