# Generated by Django 3.2.5 on 2021-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_thread_modified_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
